apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datadog-agent.fullname" . }}-configs
  labels:
    {{- include "datadog-agent.labels" . | nindent 4 }}
data:
  {{- with .Values.integrations }}
    {{- toYaml . | nindent 2 }}
  {{- end }}

