apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datadog-agent.fullname" . }}-scripts
  labels:
    {{- include "datadog-agent.labels" . | nindent 4 }}
data:
  setup: |
    cd /input
    for i in $(ls|grep .yaml); do
      folder=$(echo $i|awk -F . '{print $1}') 
      mkdir -p "/output/${folder}.d"
      cp $i "/output/${folder}.d/config.yaml"
    done
  {{- with .Values.extraScripts }}
    {{- toYaml . | nindent 2 }}
  {{- end }}

