apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datadog-agent.fullname" . }}
  labels:
    {{- include "datadog-agent.labels" . | nindent 4 }}
data:
  setup: |
  config.yaml: |
    {{- with .Values.integrations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}

